name: gxe2021
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python==3.8
  - jupyterlab
  - statsmodels
  - seaborn
  - scipy
  - rpy2
  - scikit-learn
  - numpy
  - pandas
  - pip
  - pip:
    - pyplink
